apiVersion: v1
kind: Service
metadata:
  name: teachme-apigateway-service
  labels:
    app: teachme-apigateway
spec:
  type: LoadBalancer
  selector:
    app: teachme-apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
