name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for api-gateway
        run: docker build -f APIGatewayDockerfile -t ${{ secrets.DOCKER_USERNAME }}/iteachme-apigateway:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/iteachme-apigateway:latest

      - name: Redeploy
        run: curl -X GET "${{ secrets.API_GATEWAY_DEPLOY_HOOK }}"

  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for user-service
        run: docker build -f UserServiceDockerfile -t ${{ secrets.DOCKER_USERNAME }}/iteachme-userservice:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/iteachme-userservice:latest

      - name: Redeploy
        run: curl -X GET "${{ secrets.USER_SERVICE_DEPLOY_HOOK }}"

  education-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for education-service
        run: docker build -f EducationServiceDockerfile -t ${{ secrets.DOCKER_USERNAME }}/iteachme-educationservice:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/iteachme-educationservice:latest

      - name: Redeploy
        run: curl -X GET "${{ secrets.EDUCATION_SERVICE_DEPLOY_HOOK }}"
